### ISSUE TITLE
trxdb start where left off versus stopping at stop block number

### ISSUE THREAD

**Issue by NatPDeveloper** [dfuse-io/dfuse-eosio#119]
Brief:

Running trxdb by itself to populate db.

Issue:

Started here

```2020-08-17T13:11:20.464Z (trxdb-loader) processing block (forkable/forkable.go:131){"block": "#1246626 (001305a25d7cc8638b7fe4e2ce3a253c10c14f28f20379d87d2b5546c871c431)", "new_longest_chain": true}```

And did not stop after stop block set.  How can I batch without having multiple instances overlapping one another?

With this yaml:

```
start:
  args:
  - trxdb-loader
  flags:
    trxdb-loader-batch-size: 100
    trxdb-loader-stop-block-num: 202000
```

Also tried start block 0/1, same result.
