### ISSUE TITLE
phase 3 nodeos startup failure 

### ISSUE THREAD

**Issue by NatPDeveloper** [dfuse-io/dfuse-eosio#130]
Brief:

Trying to start all services, seeing  `unsupported version of block log` nodeos error, despite me deleting both block logs (`dfuse-data/mindreader/data/blocks/blocks.log` `dfuse-data/mindreader/data/blocks/blocks.log`) and adding the flag `mindreader-no-blocks-log: true`.

Error

```
2020-08-25T19:56:41.838Z (node-manager) Unsupported version of block log. Block log version is 0 while code supports version(s) [1,3] (log_plugin/to_zap_log_plugin.go:107)
2020-08-25T19:56:41.838Z (node-manager)     {"version":0,"min":1,"max":3} (log_plugin/to_zap_log_plugin.go:107)
2020-08-25T19:56:41.838Z (node-manager)     nodeos  block_log.cpp:716 extract_chain_context (log_plugin/to_zap_log_plugin.go:107)
2020-08-25T19:56:41.838Z (node-manager)  (log_plugin/to_zap_log_plugin.go:107)
```

From [https://github.com/EOSIO/eos/blob/e19afc8072219282a7c3fc20e47aa80cb70299e4/libraries/chain/block_log.cpp#L240](https://github.com/EOSIO/eos/blob/e19afc8072219282a7c3fc20e47aa80cb70299e4/libraries/chain/block_log.cpp#L240)

Yaml

```
start:
  args:
  - abicodec
  - apiproxy
  - blockmeta
  - booter
  - dashboard
  - dgraphql
  - eosq
  - eosws
  - merger
  - mindreader
  - node-manager
  - relayer
  - search-archive
  - search-forkresolver
  - search-indexer
  - search-live
  - search-router
  - statedb
  - tokenmeta
  - trxdb-loader
  flags:
    merger-start-block-num: 118750000
    mindreader-auto-snapshot-modulo: 1000000
    mindreader-start-block-num: 118750000
    mindreader-log-to-zap: false
    mindreader-start-failure-handler: true
    mindreader-blocks-chan-capacity: 100000
    mindreader-no-blocks-log: true
    mindreader-restore-snapshot-name: 0110853697-069b7e4128deebe1b644d6e7439cff300d59c3d39343626457d33178015c7d79-snapshot.bin
    node-manager-auto-snapshot-modulo: 1000000
    node-manager-number-of-snapshots-to-keep: 5
    search-archive-start-block: 118750000
    search-indexer-start-block: 118750000
    statedb-enable-server-mode: true
    statedb-enable-inject-mode: false
    statedb-enable-pipeline: false
    trxdb-loader-start-block-num: 118750000
```

Docker

```
docker run -d -v "/newvolume/work/config/dfuse-data:/dfuse-data" -v "/newvolume/work/config/phase3/yaml:/etc/dfuseeos-configs" -v "/newvolume/work/config/mindreader:/mindreader" --name dfuse-p3-b1 dfuseeos /app/dfuseeos -c /etc/dfuseeos-configs/dfuse-p3-b1.yaml start -vv
````

Logs

[https://pastebin.com/8n36fyx5](https://pastebin.com/8n36fyx5)
