### ISSUE TITLE
phase 3 launch issues

### ISSUE THREAD

**Issue by NatPDeveloper** [dfuse-io/dfuse-eosio#131]
Brief:

Trying to run phase 3, nodeos RPC API working, dashboard/eosq/igraphql interface not connecting.  Looks like connection refused and looking locally for connection.

Eosq

<img width="1670" alt="1" src="https://user-images.githubusercontent.com/34429364/91301256-9dec0480-e772-11ea-9a0f-d10c87a288f2.png">

Dashboard

<img width="839" alt="2" src="https://user-images.githubusercontent.com/34429364/91301308-afcda780-e772-11ea-8f32-ae9ace034eb2.png">

Yaml (updated):

```
start:
  args:
  - abicodec
  - apiproxy
  - blockmeta
  - booter
  - dashboard
  - dgraphql
  - eosq
  - eosws
  - merger
  - mindreader
  - node-manager
  - relayer
  - search-archive
  - search-forkresolver
  - search-indexer
  - search-live
  - search-router
  - statedb
  - tokenmeta
  - trxdb-loader
  flags:
    apiproxy-nodeos-http-addr: ":9888"
    blockmeta-eos-api-upstream-addr: ":9888"
    booter-nodeos-api-addr: "http://localhost:9888/"
    dashboard-http-listen-addr: ":8081"
    eosws-nodeos-rpc-addr: ":9888"
    node-manager-nodeos-api-addr: ":9888"
    merger-start-block-num: 121316000
    mindreader-auto-snapshot-modulo: 1000000
    mindreader-start-block-num: 121316000
    mindreader-log-to-zap: false
    mindreader-start-failure-handler: true
    mindreader-blocks-chan-capacity: 100000
    mindreader-no-blocks-log: true
    mindreader-restore-snapshot-name: 0121316971-073b266b35579f8ce6dcebfd533886f41b585c0c9444bf39deccc81d1e889b76-snapshot.bin
    node-manager-auto-snapshot-modulo: 1000000
    node-manager-number-of-snapshots-to-keep: 5
    statedb-enable-server-mode: true
    statedb-enable-inject-mode: true
```

Docker, opening mindreader RPC, eosq, dashboard, igraphql http addresses

```
docker run -d \
-p 9888:9888 \
-p 8080:8080 \
-p 8081:8081 \
-p 13023:13023 \
-v "/newvolume/work/config/dfuse-data:/dfuse-data" \
-v "/newvolume/work/config/phase3/yaml:/etc/dfuseeos-configs" \
-v "/newvolume/work/config/mindreader:/mindreader" \
--name dfuse-p3-b1 \
dfuseeos /app/dfuseeos -c /etc/dfuseeos-configs/dfuse-p3-b1.yaml start -vv
```

Logs

[log.log](https://github.com/dfuse-io/dfuse-eosio/files/5129719/log.log)

**Comment by maoueh** [comment]
`booter-nodeos-api-addr: "http://localhost:9888/"` and the `booter` app, you should remove them, those are useful only when launching a local chain, when syncing an existing chain, it's not something you want.

**Comment by NatPDeveloper** [comment]
Need to populate search-indexer then deploy search archives

```
start:
  args:
  - search-indexer
  flags:
    search-indexer-enable-batch-mode: true
    search-indexer-shard-size: 50000
    search-indexer-start-block: 0
    search-indexer-stop-block: 121316000
```

```
start:
  args:
  - search-indexer
  flags:
    search-indexer-enable-batch-mode: true
    search-indexer-shard-size: 250
    search-indexer-start-block: 121316000
```

```
start:
  args:
  - search-archive
  flags:
    search-archive-shard-size: 50000
    search-archive-start-block: 0
    search-archive-stop-block: 121316000
```

```
start:
  args:
  - search-archive
  flags:
    search-archive-shard-size: 250
    search-archive-start-block: 121316000
```
