### ISSUE TITLE
Error executing getAccountHistoryActions in Grapher

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#210]
I run `Get Account History (Alpha) `in the test network I built and report execution timeout
`http://39.106.103.152:8081/grapher`

```
{
  "account": "eosio",
  "limit": 100
}
```

```
{
  "errors": [
    {
      "message": "graphql: timeout of 30s exceeded before completing the request (trace_id: 2ac45313be288cc75922b11432d5abb8)",
      "path": [
        "getAccountHistoryActions"
      ]
    }
  ],
  "data": null
}
```

#### dfuseeos terminal log output

`unable to complete query (resolvers/accounthist.go:90){"trace_id": "6e08337aa853e2fb3bc9247d2d8a5b7e", "error": "accounthist stream: rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp :13034: connect: connection refused\""}
`
#### dfuse.yaml
```
start:
  args:
  - abicodec
  - apiproxy
  - blockmeta
  - booter
  - dashboard
  - dgraphql
  - eosq
  - eosws
  - merger
  - mindreader
  - relayer
  - search-archive
  - search-forkresolver
  - search-indexer
  - search-live
  - search-router
  - statedb
  - tokenmeta
  - trxdb-loader
  flags: 
    apiproxy-nodeos-http-addr: :9888
    blockmeta-eos-api-upstream-addr: :9888
    eosws-nodeos-rpc-addr: :9888
    eosq-api-endpoint-url: http://39.106.103.152:8080
    dashboard-eos-node-manager-api-addr: http://39.106.103.152:8081
    common-chain-core-symbol: "8,RES"
    common-chain-id: cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f
    eosq-available-networks: "[{\"id\":\"test\",\"is_test\":true,\"logo\":\"/images/logo-eos-ore.svg\",\"name\":\"Test Network\",\"url\":\"http://39.106.103.152:8080\"}]"
    search-common-indexed-terms: "receiver, account, action, auth, scheduled, status, notif, input, event, ram.consumed, ram.released, db.key, db.table, data.account, data.active, data.active_key, data.actor, data.amount, data.auth, data.authority, data.bid, data.bidder, data.canceler, data.creator, data.executer, data.from, data.is_active, data.is_priv, data.isproxy, data.issuer, data.level, data.location, data.maximum_supply, data.name, data.newname, data.owner, data.parent, data.payer, data.permission, data.producer, data.producer_key, data.proposal_name, data.proposal_hash, data.proposer, data.proxy, data.public_key, data.producers, data.quant, data.quantity, data.ram_payer, data.receiver, data.requested, data.requirement, data.symbol, data.threshold, data.to, data.transfer, data.voter, data.voter_name, data.weight, data.abi, data.code, data.memo"

```

What is wrong with my configuration?

I run in the dfuse official test environment is normal
`https://testnet.eos.dfuse.io/graphiql/`

@maoueh
