### ISSUE TITLE
Merge and store bottleneck on local sync

### ISSUE THREAD

**Issue by maoueh** [dfuse-io/dfuse-eosio#29]
I performed a sync of Proton chain from block 0 to block 3M, then hit `Ctrl-C`. It tooks 25m between `nodeos` termination and when dfuse for EOSIO actually quit. This is because the blocks chan channel was at max capacity of 100K blocks in it. So it took roughly 25m to drain in and create the merged-blocks file from that.

Not sure when I reached that exactly, but it probably hinder my syncing performance with the Proton chain because I imagine was full relatively rapidly. Opening so we gather feedback about:
- Possibilities of improvements
- Won't fix case due to possibility to perform "parallel" sync 

Relevant files:

```
start:
  args:
  - mindreader
  flags:
    mindreader-log-to-zap: false
    mindreader-merge-and-store-directly: true
    mindreader-start-failure-handler: true
    mindreader-blocks-chan-capacity: 100000
    mindreader-restore-snapshot-name: latest
```
