### ISSUE TITLE
Bleve AnalyisWorker seems to be started even when no search app is launched

### ISSUE THREAD

**Issue by maoueh** [dfuse-io/dfuse-eosio#49]
* Version: 0.1.1
* Commit: 56eb7052e66c0d8d396dd95ce0e1f09dc0b3bb7e

While debugging an issue with `fluxdb`, and rendering the `goroutine` for a running `dfuseeos` process that was started with this config:

```
start:
  args:
  - fluxdb
  flags:
    fluxdb-enable-inject-mode: false
    fluxdb-enable-server-mode: true
    fluxdb-enable-pipeline: false
    fluxdb-http-listen-addr: :9090
    fluxdb-statedb-dsn: bigkv://<dfuse-bt-instance>/eos-kylin-flux-v8?createTable=false
```

We see those being active as a `goroutine`:

```
4 @ 0x4039110 0x4049313 0x4e397a2 0x4069721
#	0x4e397a1	github.com/blevesearch/bleve/index.AnalysisWorker+0x101	/Users/maoueh/work/pkg/mod/github.com/blevesearch/bleve@v1.0.9/index/analysis.go:102
```

This is strange because I did not expect any bleve goroutine to exist.
