### ISSUE TITLE
Support `boot` command, and kickstart a full-blown chain.

### ISSUE THREAD

**Issue by abourget** [dfuse-io/dfuse-eosio#65]
I propose we tweak `init` so it renders:

```
run:
  start:
  - boot
  - mindreader
  ...
  args:
   - --boot-if-empty=./bootseq.yaml
```

and the addition of:

```
dfuseeos boot ./path/to/bootseq.yaml  http://localhost:8888
```
and perhaps:

```
dfuseeos boot --preset mainnet --boot-options
dfuseeos boot --preset scratch
```

which uses eos-bios to fill-in your chain with something meaningful when you `start`.  It would do it optionally, probably by checking if `eosio` has a contract in place the moment `mindreader` is up and running.  The `boot` app could stay there and do nothing else after it has done its checks.

See also https://github.com/dfuse-io/dfuse-eosio/issues/54 which would benefit from this.
