### ISSUE TITLE
Global flags are not picked up from dfuse.yaml config file

### ISSUE THREAD

**Issue by sduchesneau** [dfuse-io/dfuse-eosio#74]
* flags like `log-to-file` are not parsed.
* also, it seems that `search-common-mesh-dsn`  is not picked up (while `search-common-indices-store-url` IS). This is probably related.

We want a seemless experience for those, so the user could do (from the config file):

```
start:
  args: ["relayer", "search-archive"]
  flags:
    log-to-file: false
    relayer-blah-blah: 1234
```

even if the log-to-file flag is higher in the logical hierarchy (global flag), it is still intuitive to put it under start, because it is consistent with the command-line experience.
