### ISSUE TITLE
log-format: text  no longer supported as a config flag in latest develop build

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#87]
`log-format: text` is no longer supported as a config flag in latest develop build

dfuse-config.yml contains:

```
start:
  args:
  - mindreader-stdin
  flags:
    config-file: ""
    log-to-file: false
    log-format: text
...
```
